apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-04-05T04:27:06Z"
  labels:
    app: myapp
    run: mypod
  name: mypod
  namespace: default
  resourceVersion: "4402"
  uid: 9719887c-eaa7-4659-bfe7-403693b9f475
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: mypod
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-msn8m
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: pool-lamwgu6uc-c7qip
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-msn8m
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-04-05T04:27:06Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-04-05T04:27:11Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-04-05T04:27:11Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-04-05T04:27:06Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://bca6d3ee5d284476fdef737abc4f32acf108c456398b84cb4bd0740fa48a4264
    image: docker.io/library/nginx:latest
    imageID: docker.io/library/nginx@sha256:2275af0f20d71b293916f1958f8497f987b8d8fd8113df54635f2a5915002bf1
    lastState: {}
    name: mypod
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-04-05T04:27:10Z"
  hostIP: 10.122.0.3
  phase: Running
  podIP: 10.244.0.101
  podIPs:
  - ip: 10.244.0.101
  qosClass: BestEffort
  startTime: "2022-04-05T04:27:06Z"
