apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  initContainers:
  - name: init-container1
    image: busybox
    command: ["sleep", "30"]
  - name: init-container2
    image: busybox
    command: ["sleep", "30"]
  containers:
  - name: nginx-container
    image: nginx
