apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  containers:
  - name: nginx-container
    image: nginx
    # envFrom:
    # - secretRef:
    #     name: srt1
    # env:
    # - name: username
    #   valueFrom:
    #     secretKeyRef:
    #       key: username
    #       name: srt1
    # - name: password
    #   valueFrom:
    #     secretKeyRef:
    #       key: password
    #       name: srt1
    volumeMounts:
    - name: test
      mountPath: "/secret"
      readOnly: true

  volumes:
  - name: test
    secret:
      secretName: srt1
      items:
        - key: username
          path: username

